/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.examplejdbc.view;

import co.edu.sena.examplejdbc.controller.EmployeeController;
import co.edu.sena.examplejdbc.controller.EmployeeTypeController;
import co.edu.sena.examplejdbc.controller.IEmployeeController;
import co.edu.sena.examplejdbc.controller.IEmployeeTypeController;
import co.edu.sena.examplejdbc.controller.IKeyController;
import co.edu.sena.examplejdbc.controller.IRecordController;
import co.edu.sena.examplejdbc.controller.KeyController;
import co.edu.sena.examplejdbc.controller.RecordController;
import co.edu.sena.examplejdbc.model.Employee;
import co.edu.sena.examplejdbc.model.Key;
import co.edu.sena.examplejdbc.model.Record;
import co.edu.sena.examplejdbc.utils.MessageUtils;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * date:02/04/2025
 * @author Esteban Colorado Vargas 
 * objetivo: crear la vista para record.
 */
public class JFrameRecord extends javax.swing.JFrame {

    private final IRecordController recordController = new RecordController();
    private final IEmployeeController employeeController = new EmployeeController();
    private final IKeyController keyController = new KeyController();

    /**
     * Creates new form JFrameRecord
     */
    public JFrameRecord() {
        initComponents();
        fillTable();
        fillCombos();
        insertDefaultDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltTitle = new javax.swing.JLabel();
        jLabelDescript = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelDate_Record = new javax.swing.JLabel();
        jLabelStart_Time = new javax.swing.JLabel();
        jLabelEnd_Time = new javax.swing.JLabel();
        jLabelType_id = new javax.swing.JLabel();
        jComboBoxKeyId = new javax.swing.JComboBox();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCleart = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jLabelKey_Name = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        timePickerStart = new com.github.lgooddatepicker.components.TimePicker();
        DatePickerDay = new com.github.lgooddatepicker.components.DatePicker();
        timePickerEnd = new com.github.lgooddatepicker.components.TimePicker();
        jButtonDelete1 = new javax.swing.JButton();
        jComboBoxType_id = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabeltTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabeltTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltTitle.setText("CREAR REGISTRO");
        jLabeltTitle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabeltTitle.setForeground(new java.awt.Color(255, 255, 255));

        jLabelDescript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescript.setText("Aqui  puedes insertar, actualizar, eliminar y consultar todo lo referente a la tabla Registro.");
        jLabelDescript.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDescript.setForeground(new java.awt.Color(255, 255, 255));

        jLabelId.setText("ID:");
        jLabelId.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabelDate_Record.setText("FECHA DE REGISTRO:");
        jLabelDate_Record.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelDate_Record.setForeground(new java.awt.Color(255, 255, 255));

        jLabelStart_Time.setText("HORA DE INICIO:");
        jLabelStart_Time.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelStart_Time.setForeground(new java.awt.Color(255, 255, 255));

        jLabelEnd_Time.setText("HORA DE FINALIZACION:");
        jLabelEnd_Time.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelEnd_Time.setForeground(new java.awt.Color(255, 255, 255));

        jLabelType_id.setText("ID EMPLEADO:");
        jLabelType_id.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelType_id.setForeground(new java.awt.Color(255, 255, 255));

        jButtonInsert.setText("INSERTAR");
        jButtonInsert.setBackground(new java.awt.Color(0, 255, 0));
        jButtonInsert.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 255));
        jButtonUpdate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("ELIMINAR");
        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCleart.setText("LIMPIAR");
        jButtonCleart.setBackground(new java.awt.Color(0, 204, 204));
        jButtonCleart.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonCleart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleartActionPerformed(evt);
            }
        });

        jLabelStatus.setText("ESTADO:");
        jLabelStatus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));

        jLabelKey_Name.setText("ID DE LLAVE:");
        jLabelKey_Name.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelKey_Name.setForeground(new java.awt.Color(255, 255, 255));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTREGADO", "PENDIENTE", "CANCELADO" }));

        jButtonDelete1.setText("CERRAR");
        jButtonDelete1.setBackground(new java.awt.Color(255, 153, 51));
        jButtonDelete1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDescript, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabeltTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelId)
                            .addGap(80, 80, 80))
                        .addComponent(jLabelStart_Time, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelType_id))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonInsert)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCleart)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldId)
                            .addComponent(timePickerStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxType_id, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelKey_Name)
                                .addGap(104, 104, 104)
                                .addComponent(jComboBoxKeyId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDate_Record)
                                    .addComponent(jLabelEnd_Time))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DatePickerDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(timePickerEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabeltTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescript, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStart_Time)
                            .addComponent(timePickerStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEnd_Time))
                        .addGap(31, 31, 31)
                        .addComponent(jLabelType_id))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDate_Record)
                            .addComponent(DatePickerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(timePickerEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKey_Name)
                            .addComponent(jComboBoxKeyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxType_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsert)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCleart)
                    .addComponent(jButtonDelete1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabeltTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltTitle1.setText("HISTORIAL DE REGISTROS");
        jLabeltTitle1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabeltTitle1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jLabeltTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabeltTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
//         BOTON PARA INSERTAR
        try {
            Record record = new Record();
            record.setDate_Record(DatePickerDay.getDate().toString());
            record.setStart_time(timePickerStart.getTimeStringOrEmptyString());
            record.setEnd_time(null);
            record.setEmployeeId((Employee) jComboBoxType_id.getSelectedItem());
            Key key = (Key) jComboBoxKeyId.getSelectedItem();
            record.setKey(key);
            record.setStatus(jComboBoxStatus.getSelectedItem().toString());
            recordController.insert(record);
            MessageUtils.showInfoMessage("El registro se ha insertado correctamente...");
            fillTable();
            clear();
            insertDefaultDate();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al insertar el usuario..."
                    + e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // ACTULIZAR
        try {
            Record record = new Record();
            record.setId(Integer.parseInt(jTextFieldId.getText()));
            record.setDate_Record(DatePickerDay.getDate().toString());
            record.setStart_time(timePickerStart.getTime().toString());
            record.setEnd_time(timePickerEnd.getTime() != null ? timePickerEnd.getTime().toString()
                    : null);
            record.setEmployeeId((Employee) jComboBoxType_id.getSelectedItem());
            record.setKey((Key) jComboBoxKeyId.getSelectedItem());
            record.setStatus(jComboBoxStatus.getSelectedItem().toString());
            recordController.update(record);
            MessageUtils.showInfoMessage("Registro actualizado exitosamente");
            clear();
            fillTable();
            insertDefaultDate();
        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // BOTON PARA ELIMINAR
        try {
            int option = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar el empleado?",
                    "CONFIRMAR", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                recordController.delete(Integer.parseInt(jTextFieldId.getText()));
                MessageUtils.showInfoMessage("Registro eliminado correctamente...");
                fillTable();
            }
            clear();
            insertDefaultDate();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("HUBO UN ERROR al eliminar..." + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCleartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleartActionPerformed
        // BOTON LIMPIAR
        clear();
    }//GEN-LAST:event_jButtonCleartActionPerformed

    private void jButtonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete1ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de salir?", "SALIR",
                JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonDelete1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // SELECCIONAR REGISTROS DE LA TABLA
        int rowSelected = jTable1.getSelectedRow();
        if (rowSelected != -1) {
            int idSelected = Integer.parseInt(jTable1.getValueAt(rowSelected, 0).toString());
            try {
                Record record = recordController.findById(idSelected);
                jTextFieldId.setText(String.valueOf(idSelected));
                DatePickerDay.setDate(LocalDate.parse(record.getDate_Record()));
                timePickerStart.setText(record.getStart_time());
                timePickerEnd.setText(record.getEnd_time());
                jComboBoxType_id.getModel().setSelectedItem(record.getEmployeeId());
                jComboBoxKeyId.getModel().setSelectedItem(record.getKey().toString());
                jComboBoxStatus.setSelectedItem(record.getStatus());
            } catch (Exception e) {
                MessageUtils.showErrorMessage("ERROR al usar el evento de click"
                        + e.getMessage());
            }
        }
        jButtonInsert.setEnabled(false);
        jButtonDelete.setEnabled(true);
        jButtonUpdate.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRecord().setVisible(true);
            }
        });
    }

    public void clear() {
        jTextFieldId.setText("");
        DatePickerDay.setText("");
        timePickerStart.setText("");
        timePickerEnd.setText("");
        jComboBoxType_id.setSelectedIndex(0);
        jComboBoxKeyId.setSelectedIndex(0);
        jComboBoxStatus.setSelectedIndex(0);
        jButtonInsert.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        insertDefaultDate();
    }

    public void fillTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTable1.setModel(model);
            model.addColumn("ID");
            model.addColumn("Fecha");
            model.addColumn("Hora inicio");
            model.addColumn("Hora finalizacion");
            model.addColumn("Funcionario");
            model.addColumn("LLave");
            model.addColumn("Estado");

            String[] rows = new String[7];
            List<Record> results = recordController.findAll();
            for (Record result : results) {
                rows[0] = String.valueOf(result.getId());
                rows[1] = result.getDate_Record();
                rows[2] = result.getStart_time();
                rows[3] = result.getEnd_time();
                rows[4] = result.getEmployeeId().getFullName();
                rows[5] = result.getKey().getName();
                rows[6] = result.getStatus();
                model.addRow(rows);
            }
            jTextFieldId.setEnabled(false);
            jButtonInsert.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDelete.setEnabled(false);
        } catch (Exception e) {
        }
    }

    public void fillCombos() {
        try {
            List<Employee> employees = employeeController.findAll();
            DefaultComboBoxModel modelEmployee = new DefaultComboBoxModel();
            jComboBoxType_id.setModel(modelEmployee);
            modelEmployee.addAll(employees);
            
            List<Key> allIdKeys = keyController.findAll();
            DefaultComboBoxModel modelKeys = new DefaultComboBoxModel();
            jComboBoxKeyId.setModel(modelKeys);
            modelKeys.addAll(allIdKeys);
            jComboBoxKeyId.setSelectedIndex(0);
            jComboBoxType_id.setSelectedIndex(0);

        } catch (Exception e) {
            MessageUtils.showErrorMessage(e.getMessage());
        }
    }

    public void insertDefaultDate() {
        DatePickerDay.setDate(LocalDate.now());
        timePickerStart.setTime(LocalTime.now());
        timePickerEnd.setTime(LocalTime.now());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker DatePickerDay;
    private javax.swing.JButton jButtonCleart;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDelete1;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxKeyId;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxType_id;
    private javax.swing.JLabel jLabelDate_Record;
    private javax.swing.JLabel jLabelDescript;
    private javax.swing.JLabel jLabelEnd_Time;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelKey_Name;
    private javax.swing.JLabel jLabelStart_Time;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelType_id;
    private javax.swing.JLabel jLabeltTitle;
    private javax.swing.JLabel jLabeltTitle1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldId;
    private com.github.lgooddatepicker.components.TimePicker timePickerEnd;
    private com.github.lgooddatepicker.components.TimePicker timePickerStart;
    // End of variables declaration//GEN-END:variables
}
